// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: festivaleconomia.proto

package eu.trentorise.smartcampus.service.festivaleconomia.data.message;

public final class Festivaleconomia {
  private Festivaleconomia() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EventoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string id = 1;
    boolean hasId();
    String getId();
    
    // repeated .eu.trentorise.smartcampus.service.festivaleconomia.data.message.Trans title = 2;
    java.util.List<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans> 
        getTitleList();
    eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans getTitle(int index);
    int getTitleCount();
    java.util.List<? extends eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder> 
        getTitleOrBuilderList();
    eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder getTitleOrBuilder(
        int index);
    
    // repeated .eu.trentorise.smartcampus.service.festivaleconomia.data.message.Trans description = 3;
    java.util.List<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans> 
        getDescriptionList();
    eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans getDescription(int index);
    int getDescriptionCount();
    java.util.List<? extends eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder> 
        getDescriptionOrBuilderList();
    eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder getDescriptionOrBuilder(
        int index);
    
    // repeated .eu.trentorise.smartcampus.service.festivaleconomia.data.message.Trans address = 4;
    java.util.List<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans> 
        getAddressList();
    eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans getAddress(int index);
    int getAddressCount();
    java.util.List<? extends eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder> 
        getAddressOrBuilderList();
    eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder getAddressOrBuilder(
        int index);
    
    // repeated .eu.trentorise.smartcampus.service.festivaleconomia.data.message.Trans category = 5;
    java.util.List<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans> 
        getCategoryList();
    eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans getCategory(int index);
    int getCategoryCount();
    java.util.List<? extends eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder> 
        getCategoryOrBuilderList();
    eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder getCategoryOrBuilder(
        int index);
    
    // required string url = 6;
    boolean hasUrl();
    String getUrl();
    
    // optional string image = 7;
    boolean hasImage();
    String getImage();
    
    // optional int64 lastModified = 8;
    boolean hasLastModified();
    long getLastModified();
    
    // required int64 fromTime = 9;
    boolean hasFromTime();
    long getFromTime();
    
    // optional int64 toTime = 10;
    boolean hasToTime();
    long getToTime();
  }
  public static final class Evento extends
      com.google.protobuf.GeneratedMessage
      implements EventoOrBuilder {
    // Use Evento.newBuilder() to construct.
    private Evento(Builder builder) {
      super(builder);
    }
    private Evento(boolean noInit) {}
    
    private static final Evento defaultInstance;
    public static Evento getDefaultInstance() {
      return defaultInstance;
    }
    
    public Evento getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.internal_static_eu_trentorise_smartcampus_service_festivaleconomia_data_message_Evento_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.internal_static_eu_trentorise_smartcampus_service_festivaleconomia_data_message_Evento_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .eu.trentorise.smartcampus.service.festivaleconomia.data.message.Trans title = 2;
    public static final int TITLE_FIELD_NUMBER = 2;
    private java.util.List<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans> title_;
    public java.util.List<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans> getTitleList() {
      return title_;
    }
    public java.util.List<? extends eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder> 
        getTitleOrBuilderList() {
      return title_;
    }
    public int getTitleCount() {
      return title_.size();
    }
    public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans getTitle(int index) {
      return title_.get(index);
    }
    public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder getTitleOrBuilder(
        int index) {
      return title_.get(index);
    }
    
    // repeated .eu.trentorise.smartcampus.service.festivaleconomia.data.message.Trans description = 3;
    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private java.util.List<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans> description_;
    public java.util.List<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans> getDescriptionList() {
      return description_;
    }
    public java.util.List<? extends eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder> 
        getDescriptionOrBuilderList() {
      return description_;
    }
    public int getDescriptionCount() {
      return description_.size();
    }
    public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans getDescription(int index) {
      return description_.get(index);
    }
    public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder getDescriptionOrBuilder(
        int index) {
      return description_.get(index);
    }
    
    // repeated .eu.trentorise.smartcampus.service.festivaleconomia.data.message.Trans address = 4;
    public static final int ADDRESS_FIELD_NUMBER = 4;
    private java.util.List<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans> address_;
    public java.util.List<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans> getAddressList() {
      return address_;
    }
    public java.util.List<? extends eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder> 
        getAddressOrBuilderList() {
      return address_;
    }
    public int getAddressCount() {
      return address_.size();
    }
    public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans getAddress(int index) {
      return address_.get(index);
    }
    public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder getAddressOrBuilder(
        int index) {
      return address_.get(index);
    }
    
    // repeated .eu.trentorise.smartcampus.service.festivaleconomia.data.message.Trans category = 5;
    public static final int CATEGORY_FIELD_NUMBER = 5;
    private java.util.List<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans> category_;
    public java.util.List<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans> getCategoryList() {
      return category_;
    }
    public java.util.List<? extends eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder> 
        getCategoryOrBuilderList() {
      return category_;
    }
    public int getCategoryCount() {
      return category_.size();
    }
    public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans getCategory(int index) {
      return category_.get(index);
    }
    public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder getCategoryOrBuilder(
        int index) {
      return category_.get(index);
    }
    
    // required string url = 6;
    public static final int URL_FIELD_NUMBER = 6;
    private java.lang.Object url_;
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          url_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string image = 7;
    public static final int IMAGE_FIELD_NUMBER = 7;
    private java.lang.Object image_;
    public boolean hasImage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getImage() {
      java.lang.Object ref = image_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          image_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getImageBytes() {
      java.lang.Object ref = image_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        image_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 lastModified = 8;
    public static final int LASTMODIFIED_FIELD_NUMBER = 8;
    private long lastModified_;
    public boolean hasLastModified() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getLastModified() {
      return lastModified_;
    }
    
    // required int64 fromTime = 9;
    public static final int FROMTIME_FIELD_NUMBER = 9;
    private long fromTime_;
    public boolean hasFromTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public long getFromTime() {
      return fromTime_;
    }
    
    // optional int64 toTime = 10;
    public static final int TOTIME_FIELD_NUMBER = 10;
    private long toTime_;
    public boolean hasToTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public long getToTime() {
      return toTime_;
    }
    
    private void initFields() {
      id_ = "";
      title_ = java.util.Collections.emptyList();
      description_ = java.util.Collections.emptyList();
      address_ = java.util.Collections.emptyList();
      category_ = java.util.Collections.emptyList();
      url_ = "";
      image_ = "";
      lastModified_ = 0L;
      fromTime_ = 0L;
      toTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFromTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getTitleCount(); i++) {
        if (!getTitle(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getDescriptionCount(); i++) {
        if (!getDescription(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getAddressCount(); i++) {
        if (!getAddress(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getCategoryCount(); i++) {
        if (!getCategory(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      for (int i = 0; i < title_.size(); i++) {
        output.writeMessage(2, title_.get(i));
      }
      for (int i = 0; i < description_.size(); i++) {
        output.writeMessage(3, description_.get(i));
      }
      for (int i = 0; i < address_.size(); i++) {
        output.writeMessage(4, address_.get(i));
      }
      for (int i = 0; i < category_.size(); i++) {
        output.writeMessage(5, category_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(6, getUrlBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(7, getImageBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(8, lastModified_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(9, fromTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(10, toTime_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      for (int i = 0; i < title_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, title_.get(i));
      }
      for (int i = 0; i < description_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, description_.get(i));
      }
      for (int i = 0; i < address_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, address_.get(i));
      }
      for (int i = 0; i < category_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, category_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getUrlBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getImageBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, lastModified_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, fromTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, toTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.EventoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.internal_static_eu_trentorise_smartcampus_service_festivaleconomia_data_message_Evento_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.internal_static_eu_trentorise_smartcampus_service_festivaleconomia_data_message_Evento_fieldAccessorTable;
      }
      
      // Construct using eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTitleFieldBuilder();
          getDescriptionFieldBuilder();
          getAddressFieldBuilder();
          getCategoryFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (titleBuilder_ == null) {
          title_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          titleBuilder_.clear();
        }
        if (descriptionBuilder_ == null) {
          description_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          descriptionBuilder_.clear();
        }
        if (addressBuilder_ == null) {
          address_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          addressBuilder_.clear();
        }
        if (categoryBuilder_ == null) {
          category_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          categoryBuilder_.clear();
        }
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        image_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        lastModified_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        fromTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        toTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento.getDescriptor();
      }
      
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento getDefaultInstanceForType() {
        return eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento.getDefaultInstance();
      }
      
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento build() {
        eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento buildPartial() {
        eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento result = new eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (titleBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            title_ = java.util.Collections.unmodifiableList(title_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.title_ = title_;
        } else {
          result.title_ = titleBuilder_.build();
        }
        if (descriptionBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            description_ = java.util.Collections.unmodifiableList(description_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.description_ = description_;
        } else {
          result.description_ = descriptionBuilder_.build();
        }
        if (addressBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            address_ = java.util.Collections.unmodifiableList(address_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.address_ = address_;
        } else {
          result.address_ = addressBuilder_.build();
        }
        if (categoryBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            category_ = java.util.Collections.unmodifiableList(category_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.category_ = category_;
        } else {
          result.category_ = categoryBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000002;
        }
        result.url_ = url_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000004;
        }
        result.image_ = image_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000008;
        }
        result.lastModified_ = lastModified_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000010;
        }
        result.fromTime_ = fromTime_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000020;
        }
        result.toTime_ = toTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento) {
          return mergeFrom((eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento other) {
        if (other == eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (titleBuilder_ == null) {
          if (!other.title_.isEmpty()) {
            if (title_.isEmpty()) {
              title_ = other.title_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureTitleIsMutable();
              title_.addAll(other.title_);
            }
            onChanged();
          }
        } else {
          if (!other.title_.isEmpty()) {
            if (titleBuilder_.isEmpty()) {
              titleBuilder_.dispose();
              titleBuilder_ = null;
              title_ = other.title_;
              bitField0_ = (bitField0_ & ~0x00000002);
              titleBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTitleFieldBuilder() : null;
            } else {
              titleBuilder_.addAllMessages(other.title_);
            }
          }
        }
        if (descriptionBuilder_ == null) {
          if (!other.description_.isEmpty()) {
            if (description_.isEmpty()) {
              description_ = other.description_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureDescriptionIsMutable();
              description_.addAll(other.description_);
            }
            onChanged();
          }
        } else {
          if (!other.description_.isEmpty()) {
            if (descriptionBuilder_.isEmpty()) {
              descriptionBuilder_.dispose();
              descriptionBuilder_ = null;
              description_ = other.description_;
              bitField0_ = (bitField0_ & ~0x00000004);
              descriptionBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDescriptionFieldBuilder() : null;
            } else {
              descriptionBuilder_.addAllMessages(other.description_);
            }
          }
        }
        if (addressBuilder_ == null) {
          if (!other.address_.isEmpty()) {
            if (address_.isEmpty()) {
              address_ = other.address_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureAddressIsMutable();
              address_.addAll(other.address_);
            }
            onChanged();
          }
        } else {
          if (!other.address_.isEmpty()) {
            if (addressBuilder_.isEmpty()) {
              addressBuilder_.dispose();
              addressBuilder_ = null;
              address_ = other.address_;
              bitField0_ = (bitField0_ & ~0x00000008);
              addressBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAddressFieldBuilder() : null;
            } else {
              addressBuilder_.addAllMessages(other.address_);
            }
          }
        }
        if (categoryBuilder_ == null) {
          if (!other.category_.isEmpty()) {
            if (category_.isEmpty()) {
              category_ = other.category_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureCategoryIsMutable();
              category_.addAll(other.category_);
            }
            onChanged();
          }
        } else {
          if (!other.category_.isEmpty()) {
            if (categoryBuilder_.isEmpty()) {
              categoryBuilder_.dispose();
              categoryBuilder_ = null;
              category_ = other.category_;
              bitField0_ = (bitField0_ & ~0x00000010);
              categoryBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCategoryFieldBuilder() : null;
            } else {
              categoryBuilder_.addAllMessages(other.category_);
            }
          }
        }
        if (other.hasUrl()) {
          setUrl(other.getUrl());
        }
        if (other.hasImage()) {
          setImage(other.getImage());
        }
        if (other.hasLastModified()) {
          setLastModified(other.getLastModified());
        }
        if (other.hasFromTime()) {
          setFromTime(other.getFromTime());
        }
        if (other.hasToTime()) {
          setToTime(other.getToTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasUrl()) {
          
          return false;
        }
        if (!hasFromTime()) {
          
          return false;
        }
        for (int i = 0; i < getTitleCount(); i++) {
          if (!getTitle(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getDescriptionCount(); i++) {
          if (!getDescription(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getAddressCount(); i++) {
          if (!getAddress(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getCategoryCount(); i++) {
          if (!getCategory(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder subBuilder = eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addTitle(subBuilder.buildPartial());
              break;
            }
            case 26: {
              eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder subBuilder = eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addDescription(subBuilder.buildPartial());
              break;
            }
            case 34: {
              eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder subBuilder = eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAddress(subBuilder.buildPartial());
              break;
            }
            case 42: {
              eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder subBuilder = eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addCategory(subBuilder.buildPartial());
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              url_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              image_ = input.readBytes();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              lastModified_ = input.readInt64();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              fromTime_ = input.readInt64();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              toTime_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // repeated .eu.trentorise.smartcampus.service.festivaleconomia.data.message.Trans title = 2;
      private java.util.List<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans> title_ =
        java.util.Collections.emptyList();
      private void ensureTitleIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          title_ = new java.util.ArrayList<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans>(title_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder> titleBuilder_;
      
      public java.util.List<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans> getTitleList() {
        if (titleBuilder_ == null) {
          return java.util.Collections.unmodifiableList(title_);
        } else {
          return titleBuilder_.getMessageList();
        }
      }
      public int getTitleCount() {
        if (titleBuilder_ == null) {
          return title_.size();
        } else {
          return titleBuilder_.getCount();
        }
      }
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans getTitle(int index) {
        if (titleBuilder_ == null) {
          return title_.get(index);
        } else {
          return titleBuilder_.getMessage(index);
        }
      }
      public Builder setTitle(
          int index, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans value) {
        if (titleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTitleIsMutable();
          title_.set(index, value);
          onChanged();
        } else {
          titleBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setTitle(
          int index, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder builderForValue) {
        if (titleBuilder_ == null) {
          ensureTitleIsMutable();
          title_.set(index, builderForValue.build());
          onChanged();
        } else {
          titleBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addTitle(eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans value) {
        if (titleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTitleIsMutable();
          title_.add(value);
          onChanged();
        } else {
          titleBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addTitle(
          int index, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans value) {
        if (titleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTitleIsMutable();
          title_.add(index, value);
          onChanged();
        } else {
          titleBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addTitle(
          eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder builderForValue) {
        if (titleBuilder_ == null) {
          ensureTitleIsMutable();
          title_.add(builderForValue.build());
          onChanged();
        } else {
          titleBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addTitle(
          int index, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder builderForValue) {
        if (titleBuilder_ == null) {
          ensureTitleIsMutable();
          title_.add(index, builderForValue.build());
          onChanged();
        } else {
          titleBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllTitle(
          java.lang.Iterable<? extends eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans> values) {
        if (titleBuilder_ == null) {
          ensureTitleIsMutable();
          super.addAll(values, title_);
          onChanged();
        } else {
          titleBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearTitle() {
        if (titleBuilder_ == null) {
          title_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          titleBuilder_.clear();
        }
        return this;
      }
      public Builder removeTitle(int index) {
        if (titleBuilder_ == null) {
          ensureTitleIsMutable();
          title_.remove(index);
          onChanged();
        } else {
          titleBuilder_.remove(index);
        }
        return this;
      }
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder getTitleBuilder(
          int index) {
        return getTitleFieldBuilder().getBuilder(index);
      }
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder getTitleOrBuilder(
          int index) {
        if (titleBuilder_ == null) {
          return title_.get(index);  } else {
          return titleBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder> 
           getTitleOrBuilderList() {
        if (titleBuilder_ != null) {
          return titleBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(title_);
        }
      }
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder addTitleBuilder() {
        return getTitleFieldBuilder().addBuilder(
            eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.getDefaultInstance());
      }
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder addTitleBuilder(
          int index) {
        return getTitleFieldBuilder().addBuilder(
            index, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.getDefaultInstance());
      }
      public java.util.List<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder> 
           getTitleBuilderList() {
        return getTitleFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder> 
          getTitleFieldBuilder() {
        if (titleBuilder_ == null) {
          titleBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder>(
                  title_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          title_ = null;
        }
        return titleBuilder_;
      }
      
      // repeated .eu.trentorise.smartcampus.service.festivaleconomia.data.message.Trans description = 3;
      private java.util.List<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans> description_ =
        java.util.Collections.emptyList();
      private void ensureDescriptionIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          description_ = new java.util.ArrayList<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans>(description_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder> descriptionBuilder_;
      
      public java.util.List<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans> getDescriptionList() {
        if (descriptionBuilder_ == null) {
          return java.util.Collections.unmodifiableList(description_);
        } else {
          return descriptionBuilder_.getMessageList();
        }
      }
      public int getDescriptionCount() {
        if (descriptionBuilder_ == null) {
          return description_.size();
        } else {
          return descriptionBuilder_.getCount();
        }
      }
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans getDescription(int index) {
        if (descriptionBuilder_ == null) {
          return description_.get(index);
        } else {
          return descriptionBuilder_.getMessage(index);
        }
      }
      public Builder setDescription(
          int index, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans value) {
        if (descriptionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDescriptionIsMutable();
          description_.set(index, value);
          onChanged();
        } else {
          descriptionBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setDescription(
          int index, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder builderForValue) {
        if (descriptionBuilder_ == null) {
          ensureDescriptionIsMutable();
          description_.set(index, builderForValue.build());
          onChanged();
        } else {
          descriptionBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addDescription(eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans value) {
        if (descriptionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDescriptionIsMutable();
          description_.add(value);
          onChanged();
        } else {
          descriptionBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addDescription(
          int index, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans value) {
        if (descriptionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDescriptionIsMutable();
          description_.add(index, value);
          onChanged();
        } else {
          descriptionBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addDescription(
          eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder builderForValue) {
        if (descriptionBuilder_ == null) {
          ensureDescriptionIsMutable();
          description_.add(builderForValue.build());
          onChanged();
        } else {
          descriptionBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addDescription(
          int index, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder builderForValue) {
        if (descriptionBuilder_ == null) {
          ensureDescriptionIsMutable();
          description_.add(index, builderForValue.build());
          onChanged();
        } else {
          descriptionBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllDescription(
          java.lang.Iterable<? extends eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans> values) {
        if (descriptionBuilder_ == null) {
          ensureDescriptionIsMutable();
          super.addAll(values, description_);
          onChanged();
        } else {
          descriptionBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearDescription() {
        if (descriptionBuilder_ == null) {
          description_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          descriptionBuilder_.clear();
        }
        return this;
      }
      public Builder removeDescription(int index) {
        if (descriptionBuilder_ == null) {
          ensureDescriptionIsMutable();
          description_.remove(index);
          onChanged();
        } else {
          descriptionBuilder_.remove(index);
        }
        return this;
      }
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder getDescriptionBuilder(
          int index) {
        return getDescriptionFieldBuilder().getBuilder(index);
      }
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder getDescriptionOrBuilder(
          int index) {
        if (descriptionBuilder_ == null) {
          return description_.get(index);  } else {
          return descriptionBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder> 
           getDescriptionOrBuilderList() {
        if (descriptionBuilder_ != null) {
          return descriptionBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(description_);
        }
      }
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder addDescriptionBuilder() {
        return getDescriptionFieldBuilder().addBuilder(
            eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.getDefaultInstance());
      }
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder addDescriptionBuilder(
          int index) {
        return getDescriptionFieldBuilder().addBuilder(
            index, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.getDefaultInstance());
      }
      public java.util.List<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder> 
           getDescriptionBuilderList() {
        return getDescriptionFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder> 
          getDescriptionFieldBuilder() {
        if (descriptionBuilder_ == null) {
          descriptionBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder>(
                  description_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          description_ = null;
        }
        return descriptionBuilder_;
      }
      
      // repeated .eu.trentorise.smartcampus.service.festivaleconomia.data.message.Trans address = 4;
      private java.util.List<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans> address_ =
        java.util.Collections.emptyList();
      private void ensureAddressIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          address_ = new java.util.ArrayList<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans>(address_);
          bitField0_ |= 0x00000008;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder> addressBuilder_;
      
      public java.util.List<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans> getAddressList() {
        if (addressBuilder_ == null) {
          return java.util.Collections.unmodifiableList(address_);
        } else {
          return addressBuilder_.getMessageList();
        }
      }
      public int getAddressCount() {
        if (addressBuilder_ == null) {
          return address_.size();
        } else {
          return addressBuilder_.getCount();
        }
      }
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans getAddress(int index) {
        if (addressBuilder_ == null) {
          return address_.get(index);
        } else {
          return addressBuilder_.getMessage(index);
        }
      }
      public Builder setAddress(
          int index, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressIsMutable();
          address_.set(index, value);
          onChanged();
        } else {
          addressBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setAddress(
          int index, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder builderForValue) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          address_.set(index, builderForValue.build());
          onChanged();
        } else {
          addressBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAddress(eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressIsMutable();
          address_.add(value);
          onChanged();
        } else {
          addressBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addAddress(
          int index, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressIsMutable();
          address_.add(index, value);
          onChanged();
        } else {
          addressBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addAddress(
          eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder builderForValue) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          address_.add(builderForValue.build());
          onChanged();
        } else {
          addressBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addAddress(
          int index, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder builderForValue) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          address_.add(index, builderForValue.build());
          onChanged();
        } else {
          addressBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllAddress(
          java.lang.Iterable<? extends eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans> values) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          super.addAll(values, address_);
          onChanged();
        } else {
          addressBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearAddress() {
        if (addressBuilder_ == null) {
          address_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          addressBuilder_.clear();
        }
        return this;
      }
      public Builder removeAddress(int index) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          address_.remove(index);
          onChanged();
        } else {
          addressBuilder_.remove(index);
        }
        return this;
      }
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder getAddressBuilder(
          int index) {
        return getAddressFieldBuilder().getBuilder(index);
      }
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder getAddressOrBuilder(
          int index) {
        if (addressBuilder_ == null) {
          return address_.get(index);  } else {
          return addressBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder> 
           getAddressOrBuilderList() {
        if (addressBuilder_ != null) {
          return addressBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(address_);
        }
      }
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder addAddressBuilder() {
        return getAddressFieldBuilder().addBuilder(
            eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.getDefaultInstance());
      }
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder addAddressBuilder(
          int index) {
        return getAddressFieldBuilder().addBuilder(
            index, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.getDefaultInstance());
      }
      public java.util.List<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder> 
           getAddressBuilderList() {
        return getAddressFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder> 
          getAddressFieldBuilder() {
        if (addressBuilder_ == null) {
          addressBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder>(
                  address_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          address_ = null;
        }
        return addressBuilder_;
      }
      
      // repeated .eu.trentorise.smartcampus.service.festivaleconomia.data.message.Trans category = 5;
      private java.util.List<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans> category_ =
        java.util.Collections.emptyList();
      private void ensureCategoryIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          category_ = new java.util.ArrayList<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans>(category_);
          bitField0_ |= 0x00000010;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder> categoryBuilder_;
      
      public java.util.List<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans> getCategoryList() {
        if (categoryBuilder_ == null) {
          return java.util.Collections.unmodifiableList(category_);
        } else {
          return categoryBuilder_.getMessageList();
        }
      }
      public int getCategoryCount() {
        if (categoryBuilder_ == null) {
          return category_.size();
        } else {
          return categoryBuilder_.getCount();
        }
      }
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans getCategory(int index) {
        if (categoryBuilder_ == null) {
          return category_.get(index);
        } else {
          return categoryBuilder_.getMessage(index);
        }
      }
      public Builder setCategory(
          int index, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans value) {
        if (categoryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCategoryIsMutable();
          category_.set(index, value);
          onChanged();
        } else {
          categoryBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setCategory(
          int index, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder builderForValue) {
        if (categoryBuilder_ == null) {
          ensureCategoryIsMutable();
          category_.set(index, builderForValue.build());
          onChanged();
        } else {
          categoryBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addCategory(eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans value) {
        if (categoryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCategoryIsMutable();
          category_.add(value);
          onChanged();
        } else {
          categoryBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addCategory(
          int index, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans value) {
        if (categoryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCategoryIsMutable();
          category_.add(index, value);
          onChanged();
        } else {
          categoryBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addCategory(
          eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder builderForValue) {
        if (categoryBuilder_ == null) {
          ensureCategoryIsMutable();
          category_.add(builderForValue.build());
          onChanged();
        } else {
          categoryBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addCategory(
          int index, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder builderForValue) {
        if (categoryBuilder_ == null) {
          ensureCategoryIsMutable();
          category_.add(index, builderForValue.build());
          onChanged();
        } else {
          categoryBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllCategory(
          java.lang.Iterable<? extends eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans> values) {
        if (categoryBuilder_ == null) {
          ensureCategoryIsMutable();
          super.addAll(values, category_);
          onChanged();
        } else {
          categoryBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearCategory() {
        if (categoryBuilder_ == null) {
          category_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          categoryBuilder_.clear();
        }
        return this;
      }
      public Builder removeCategory(int index) {
        if (categoryBuilder_ == null) {
          ensureCategoryIsMutable();
          category_.remove(index);
          onChanged();
        } else {
          categoryBuilder_.remove(index);
        }
        return this;
      }
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder getCategoryBuilder(
          int index) {
        return getCategoryFieldBuilder().getBuilder(index);
      }
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder getCategoryOrBuilder(
          int index) {
        if (categoryBuilder_ == null) {
          return category_.get(index);  } else {
          return categoryBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder> 
           getCategoryOrBuilderList() {
        if (categoryBuilder_ != null) {
          return categoryBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(category_);
        }
      }
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder addCategoryBuilder() {
        return getCategoryFieldBuilder().addBuilder(
            eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.getDefaultInstance());
      }
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder addCategoryBuilder(
          int index) {
        return getCategoryFieldBuilder().addBuilder(
            index, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.getDefaultInstance());
      }
      public java.util.List<eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder> 
           getCategoryBuilderList() {
        return getCategoryFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder> 
          getCategoryFieldBuilder() {
        if (categoryBuilder_ == null) {
          categoryBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder, eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder>(
                  category_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          category_ = null;
        }
        return categoryBuilder_;
      }
      
      // required string url = 6;
      private java.lang.Object url_ = "";
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUrl(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        url_ = value;
        onChanged();
        return this;
      }
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000020);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      void setUrl(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        url_ = value;
        onChanged();
      }
      
      // optional string image = 7;
      private java.lang.Object image_ = "";
      public boolean hasImage() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getImage() {
        java.lang.Object ref = image_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          image_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setImage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        image_ = value;
        onChanged();
        return this;
      }
      public Builder clearImage() {
        bitField0_ = (bitField0_ & ~0x00000040);
        image_ = getDefaultInstance().getImage();
        onChanged();
        return this;
      }
      void setImage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        image_ = value;
        onChanged();
      }
      
      // optional int64 lastModified = 8;
      private long lastModified_ ;
      public boolean hasLastModified() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public long getLastModified() {
        return lastModified_;
      }
      public Builder setLastModified(long value) {
        bitField0_ |= 0x00000080;
        lastModified_ = value;
        onChanged();
        return this;
      }
      public Builder clearLastModified() {
        bitField0_ = (bitField0_ & ~0x00000080);
        lastModified_ = 0L;
        onChanged();
        return this;
      }
      
      // required int64 fromTime = 9;
      private long fromTime_ ;
      public boolean hasFromTime() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public long getFromTime() {
        return fromTime_;
      }
      public Builder setFromTime(long value) {
        bitField0_ |= 0x00000100;
        fromTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearFromTime() {
        bitField0_ = (bitField0_ & ~0x00000100);
        fromTime_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int64 toTime = 10;
      private long toTime_ ;
      public boolean hasToTime() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public long getToTime() {
        return toTime_;
      }
      public Builder setToTime(long value) {
        bitField0_ |= 0x00000200;
        toTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearToTime() {
        bitField0_ = (bitField0_ & ~0x00000200);
        toTime_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:eu.trentorise.smartcampus.service.festivaleconomia.data.message.Evento)
    }
    
    static {
      defaultInstance = new Evento(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:eu.trentorise.smartcampus.service.festivaleconomia.data.message.Evento)
  }
  
  public interface TransOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string lang = 1;
    boolean hasLang();
    String getLang();
    
    // required string value = 2;
    boolean hasValue();
    String getValue();
  }
  public static final class Trans extends
      com.google.protobuf.GeneratedMessage
      implements TransOrBuilder {
    // Use Trans.newBuilder() to construct.
    private Trans(Builder builder) {
      super(builder);
    }
    private Trans(boolean noInit) {}
    
    private static final Trans defaultInstance;
    public static Trans getDefaultInstance() {
      return defaultInstance;
    }
    
    public Trans getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.internal_static_eu_trentorise_smartcampus_service_festivaleconomia_data_message_Trans_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.internal_static_eu_trentorise_smartcampus_service_festivaleconomia_data_message_Trans_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string lang = 1;
    public static final int LANG_FIELD_NUMBER = 1;
    private java.lang.Object lang_;
    public boolean hasLang() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getLang() {
      java.lang.Object ref = lang_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          lang_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLangBytes() {
      java.lang.Object ref = lang_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        lang_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.Object value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          value_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      lang_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasLang()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getLangBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getLangBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.TransOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.internal_static_eu_trentorise_smartcampus_service_festivaleconomia_data_message_Trans_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.internal_static_eu_trentorise_smartcampus_service_festivaleconomia_data_message_Trans_fieldAccessorTable;
      }
      
      // Construct using eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        lang_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.getDescriptor();
      }
      
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans getDefaultInstanceForType() {
        return eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.getDefaultInstance();
      }
      
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans build() {
        eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans buildPartial() {
        eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans result = new eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.lang_ = lang_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans) {
          return mergeFrom((eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans other) {
        if (other == eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.getDefaultInstance()) return this;
        if (other.hasLang()) {
          setLang(other.getLang());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasLang()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              lang_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string lang = 1;
      private java.lang.Object lang_ = "";
      public boolean hasLang() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getLang() {
        java.lang.Object ref = lang_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          lang_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLang(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        lang_ = value;
        onChanged();
        return this;
      }
      public Builder clearLang() {
        bitField0_ = (bitField0_ & ~0x00000001);
        lang_ = getDefaultInstance().getLang();
        onChanged();
        return this;
      }
      void setLang(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        lang_ = value;
        onChanged();
      }
      
      // required string value = 2;
      private java.lang.Object value_ = "";
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      void setValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:eu.trentorise.smartcampus.service.festivaleconomia.data.message.Trans)
    }
    
    static {
      defaultInstance = new Trans(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:eu.trentorise.smartcampus.service.festivaleconomia.data.message.Trans)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_trentorise_smartcampus_service_festivaleconomia_data_message_Evento_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_trentorise_smartcampus_service_festivaleconomia_data_message_Evento_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_trentorise_smartcampus_service_festivaleconomia_data_message_Trans_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_trentorise_smartcampus_service_festivaleconomia_data_message_Trans_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026festivaleconomia.proto\022?eu.trentorise." +
      "smartcampus.service.festivaleconomia.dat" +
      "a.message\"\317\003\n\006Evento\022\n\n\002id\030\001 \002(\t\022U\n\005titl" +
      "e\030\002 \003(\0132F.eu.trentorise.smartcampus.serv" +
      "ice.festivaleconomia.data.message.Trans\022" +
      "[\n\013description\030\003 \003(\0132F.eu.trentorise.sma" +
      "rtcampus.service.festivaleconomia.data.m" +
      "essage.Trans\022W\n\007address\030\004 \003(\0132F.eu.trent" +
      "orise.smartcampus.service.festivaleconom" +
      "ia.data.message.Trans\022X\n\010category\030\005 \003(\0132",
      "F.eu.trentorise.smartcampus.service.fest" +
      "ivaleconomia.data.message.Trans\022\013\n\003url\030\006" +
      " \002(\t\022\r\n\005image\030\007 \001(\t\022\024\n\014lastModified\030\010 \001(" +
      "\003\022\020\n\010fromTime\030\t \002(\003\022\016\n\006toTime\030\n \001(\003\"$\n\005T" +
      "rans\022\014\n\004lang\030\001 \002(\t\022\r\n\005value\030\002 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_eu_trentorise_smartcampus_service_festivaleconomia_data_message_Evento_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_eu_trentorise_smartcampus_service_festivaleconomia_data_message_Evento_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eu_trentorise_smartcampus_service_festivaleconomia_data_message_Evento_descriptor,
              new java.lang.String[] { "Id", "Title", "Description", "Address", "Category", "Url", "Image", "LastModified", "FromTime", "ToTime", },
              eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento.class,
              eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Evento.Builder.class);
          internal_static_eu_trentorise_smartcampus_service_festivaleconomia_data_message_Trans_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_eu_trentorise_smartcampus_service_festivaleconomia_data_message_Trans_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eu_trentorise_smartcampus_service_festivaleconomia_data_message_Trans_descriptor,
              new java.lang.String[] { "Lang", "Value", },
              eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.class,
              eu.trentorise.smartcampus.service.festivaleconomia.data.message.Festivaleconomia.Trans.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
